import {
  giftCover2,
  giftCover3,
  giftCover4,
  giftCover5,
  giftCover6,
  workshopImg1,
  workshopImg2,
  workshopImg3,
  workshopImg4,
  workshopImg5,
  workshopImg6,
  workshopImg7,
  workshopImg8,
  workshopImg9,
  white2,
  white4,
  white7,
  gray1,
  gray2,
  gray3,
  gray5,
  black1,
  black2,
  black3,
  black4,
  black5,
  black6,
  white6,
  blue1,
  blue2,
  blue3,
  blue4,
  white9,
  black8,
  blue5,
  gray6,
  black9,
  white10,
  gray7,
  black10,
  white11,
  blue6,
  blue7,
  gray8,
  white12,
  blue8,
  black11,
  blue9,
  gray9,
  white13,
  gray10,
  white5,
  black12,
  gray11,
  black13,
  blue10,
  gift1,
  gift2,
  blue11,
  pot1,
  pot2,
  pot3,
  pot4,
  pot5,
  pot6,
  pot7,
  pot8,
  care1,
  care2,
  care3,
  care5,
  care6,
  care7,
  care8,
  care9,
  care10,
  care12,
  care11,
  potcare1,
  potcare2,
  potcare3,
  potcare4,
  care13,
  care14,
  care15,
  care16,
  care17,
  care18,
  care19,
  care20,
  white7_1,
  white7_2,
  black1_1,
  black1_2,
  gray1_1,
  gray1_2,
  blue11_1,
  blue1_1,
  blue1_2,
  white2_1,
  white2_2,
  gray2_1,
  gray2_2,
  black2_1,
  black2_2,
  black4_1,
  black4_2,
  gray3_1,
  gray3_2,
  white4_1,
  white4_2,
  black3_1,
  black3_2,
  blue3_1,
  blue3_2,
  blue4_1,
  blue4_2,
  white6_1,
  white6_2,
  gray12,
  gray12_1,
  gray12_2,
  black5_1,
  black5_2,
  black6_1,
  black6_2,
  white9_1,
  white9_2,
  blue5_1,
  blue5_2,
  gray6_1,
  gray6_2,
  black9_1,
  white10_1,
  gray7_1,
  gray7_2,
  black10_1,
  black10_2,
  white12_1,
  white12_2,
  blue8_1,
  blue8_2,
  black11_1,
  black11_2,
  blue9_1,
  blue9_2,
  gray9_1,
  gray9_2,
  white13_1,
  white13_2,
  gray10_1,
  black12_1,
  gray11_1,
  gray11_2,
  black13_1,
  black13_2,
  blue10_1,
  blue10_2,
  potcare5,
  takeCare1,
  takeCare2,
  takeCare3,
   illustration1,
  illustration2,
  illustration3,
} from '../assets'

import { v4 as uuidv4 } from 'uuid'

export const plantsData = [
  {
    id: 1,
    img: white7,
    photos: [white7, white7_1, white7_2],
    title: 'Money Three',
    stars: 70,
    position: 'discounted',
    ExPrice: 175.0,
    price: 125.0,
    category: 'Indoor',
    color: 'White',
    potSize: '12.5-15cm',
    careLevel: 'hard',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },
  {
    id: 2,
    img: black1,
    photos: [black1, black1_1, black1_2],
    title: 'Bromeliad Guzmania',
    stars: 46,
    position: 'discounted',
    price: 45.0,
    ExPrice: 75.0,
    category: 'Outdoor',
    color: 'Black',
    potSize: '12.5-15cm',
    careLevel: 'hard',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },
  {
    id: 3,
    img: gray1,
    photos: [gray1, gray1_1, gray1_2],
    title: 'Hoya Heart',
    price: 75.0,
    stars: 78,
    position: 'bestSellers',
    category: 'Outdoor',
    color: 'Gray',
    potSize: '12.5-15cm',
    careLevel: 'easy',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },
  {
    id: 4,
    img: blue11,
    photos: [blue11, gift1, blue11_1],
    title: 'Cat Palm',
    stars: 28,
    position: 'discounted',
    price: 66.0,
    ExPrice: 75.0,
    category: 'Indoor',
    color: 'Blue',
    potSize: '16cm',
    careLevel: 'moderate',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },
  {
    id: 5,
    img: blue1,
    photos: [blue1, blue1_1, blue1_2],
    title: 'Guzmania',
    price: 75.0,
    stars: 69,
    position: 'bestSellers',
    category: 'Pet Friendly',
    color: 'Blue',
    potSize: '15-19cm',
    careLevel: 'moderate',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },
  {
    id: 6,
    img: white2,
    photos: [white2, white2_1, white2_2],
    title: 'Peace Lily',
    price: 75.0,
    stars: 7,
    position: 'New',
    category: 'Outdoor',
    color: 'White',
    potSize: '20-22cm',
    careLevel: 'hard',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },
  {
    id: 7,
    img: gray2,
    photos: [gray2, gray2_1, gray2_2],
    title: 'Easy Peasy',
    stars: 54,
    position: 'discounted',
    price: 59.0,
    ExPrice: 89.0,
    category: 'Pet Friendly',
    color: 'Gray',
    potSize: '20-22cm',
    careLevel: 'moderate',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },
  {
    id: 8,
    img: black2,
    photos: [black2, black2_1, black2_2],
    title: 'Stromanthe Triostar',
    stars: 33,
    position: 'discounted',
    price: 69.0,
    ExPrice: 79.0,
    category: 'Indoor',
    color: 'Black',
    potSize: '16cm',
    careLevel: 'easy',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },
  {
    id: 9,
    img: black4,
    photos: [black4, black4_1, black4_2],
    title: 'Leaf Fig',
    stars: 78,
    position: 'discounted',
    price: 60.0,
    ExPrice: 75.0,
    category: 'Indoor',
    color: 'Black',
    potSize: '20-22cm',
    careLevel: 'easy',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },

  {
    id: 10,
    img: gray3,
    photos: [gray3, gray3_1, gray3_2],
    title: 'Monstera',
    stars: 41,
    position: 'discounted',
    price: 49.0,
    ExPrice: 79.0,
    category: 'Pet Friendly',
    color: 'Gray',
    potSize: '16cm',
    careLevel: 'moderate',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },
  {
    id: 11,
    img: white4,
    photos: [white4, white4_1, white4_2],
    title: 'Chinese Palm',
    stars: 48,
    position: 'discounted',
    price: 49.0,
    ExPrice: 89.0,
    category: 'Pet Friendly',
    color: 'White',
    potSize: '12.5-15cm',
    careLevel: 'hard',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },
  {
    id: 12,
    img: black3,
    photos: [black3, black3_1, black3_2],
    title: 'ZZ Plant',
    price: 79.0,
    stars: 67,
    position: 'bestSellers',
    category: 'Pet Friendly',
    color: 'Black',
    potSize: '12.5-15cm',
    careLevel: 'moderate',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },
  {
    id: 13,
    img: blue2,
    photos: [blue2, gray2_1, gray2_2],
    title: 'Bird Of Paradise',
    price: 75.0,
    stars: 56,
    position: 'bestSellers',
    category: 'Outdoor',
    color: 'Blue',
    potSize: '12.5-15cm',
    careLevel: 'hard',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },
  {
    id: 14,
    img: blue3,
    photos: [blue3, blue3_1, blue3_2],
    title: 'Money Tree',
    price: 69.0,
    stars: 55,
    position: 'bestSellers',
    category: 'Indoor',
    color: 'Blue',
    potSize: '16cm',
    careLevel: 'easy',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },
  {
    id: 15,
    img: blue4,
    photos: [blue4, blue4_1, blue4_2],
    title: 'Sansevieria',
    price: 79.0,
    stars: 71,
    position: 'bestSellers',
    category: 'Pet Friendly',
    color: 'Blue',
    potSize: '15-19cm',
    careLevel: 'moderate',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },
  {
    id: 16,
    img: white6,
    photos: [white6, white6_1, white6_2],
    title: 'Ficus Ginseng',
    stars: 24,
    position: 'discounted',
    price: 39.0,
    ExPrice: 79.0,
    category: 'Indoor',
    color: 'White',
    potSize: '15-19cm',
    careLevel: 'hard',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },
  {
    id: 17,
    img: gray12,
    photos: [gray12, gray12_1, gray12_2],
    title: 'Pet Favorite',
    stars: 19,
    position: 'discounted',
    price: 22.0,
    ExPrice: 49.0,
    category: 'Pet Friendly',
    color: 'Gray',
    potSize: '15-19cm',
    careLevel: 'hard',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },
  {
    id: 18,
    img: black5,
    photos: [black5, black5_1, black5_2],
    title: 'Pet-Friendly Duo',
    stars: 27,
    position: 'new',
    price: 79.0,
    category: 'Outdoor',
    color: 'Black',
    potSize: '15-19cm',
    careLevel: 'moderate',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },
  {
    id: 19,
    img: black6,
    photos: [black6, black6_1, black6_2],
    title: 'Summer Plant',
    stars: 73,
    position: 'new',
    price: 79.0,
    category: 'Indoor',
    color: 'Black',
    potSize: '16cm',
    careLevel: 'moderate',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },
  {
    id: 20,
    img: gray5,
    photos: [gray5, black6_1, black6_2],
    title: 'Sansevieria Zeylanica',
    stars: 12,
    position: 'discounted',
    price: 69.0,
    ExPrice: 89.0,
    category: 'Pet Friendly',
    color: 'Gray',
    potSize: '20-22cm',
    careLevel: 'easy',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },
  {
    id: 21,
    img: white9,
    photos: [white9, white9_1, white9_2],
    title: 'Felicity',
    stars: 23,
    position: 'New',
    price: 68.0,
    category: 'Indoor',
    color: 'White',
    potSize: '16cm',
    careLevel: 'moderate',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },
  {
    id: 22,
    img: black8,
    photos: [black8, black6_1, black6_2],
    title: 'Mini Money Tree',
    stars: 50,
    position: 'New',
    price: 49.0,
    category: 'Outdoor',
    color: 'Black',
    potSize: '20-22cm',
    careLevel: 'moderate',
    description:
      'A lively, pet-friendly plant topped with palmate leaves upon a stout trunk. A mini-version of the beloved braided Money Tree',
  },
  {
    id: 23,
    img: blue5,
    photos: [blue5, blue5_1, blue5_2],
    title: 'Colorful Collection',
    stars: 76,
    position: 'discounted',
    price: 85.0,
    ExPrice: 115.0,
    category: 'Pet Friendly',
    color: 'Blue',
    potSize: '20-22cm',
    careLevel: 'moderate',
    description:
      'If your space is needing a burst of color, look no further than the Colorful Collection. The Red Anthurium, Yellow Bromeliad, and Bromeliad Summer each include their own vibrant, long-lasting flowers that will brighten up your home.',
  },
  {
    id: 24,
    img: gray6,
    photos: [gray6, gray6_1, gray6_2],
    title: 'Variegated Schefflera',
    stars: 46,
    position: 'New',
    price: 99.0,
    category: 'Outdoor',
    color: 'Gray',
    potSize: '15-19cm',
    careLevel: 'hard',
    description:
      'If your space is needing a burst of color, look no further than the Colorful Collection. The Red Anthurium, Yellow Bromeliad, and Bromeliad Summer each include their own vibrant, long-lasting flowers that will brighten up your home.',
  },
  {
    id: 25,
    img: black9,
    photos: [black9, black9_1, gray2_1],
    title: 'Mini Beginner Set',
    stars: 41,
    position: 'New',
    price: 116.0,
    category: 'Indoor',
    color: 'Black',
    potSize: '20-22cm',
    careLevel: 'hard',
    description:
      'Whether you’re just starting your plant parent journey or you want to help a loved one get started on theirs, the Mini Beginner set has you covered. Meet the easy-going Hedgehog Aloe, delightful Money Tree, and classic Philodendron Heartleaf.',
  },
  {
    id: 26,
    img: white10,
    photos: [white10, black4_2, white10_1],
    title: 'Decorator Duo',
    stars: 56,
    position: 'bestSellers',
    price: 129.0,
    category: 'Outdoor',
    color: 'White',
    potSize: '12.5-15cm',
    careLevel: 'hard',
    description:
      'Name a more iconic duo; we’ll wait! The popular Whalefin Sansevieria and jazzy Ponytail Palm are here to liven up any collection with minimal maintenance. These party animals are perfect for virtually any spot in your home or make a fun gift for any occasion.',
  },
  {
    id: 27,
    img: gray7,
    photos: [gray7, gray7_1, gray7_2],
    title: 'Kitchen Bundle',
    stars: 12,
    position: 'New',
    price: 82.0,
    category: 'Pet Friendly',
    color: 'Gray',
    potSize: '16cm',
    careLevel: 'moderate',
    description:
      'Put nature at the heart of your home with the Kitchen Bundle. This bundle features the fun Bromeliad Pineapple and charming Calathea Freddie. Whether your kitchen is filled or dappled with sunshine, these plants can live happily in almost any spot. This pair of plants also love the naturally warm and humid environment of the kitchen.',
  },
  {
    id: 28,
    img: black10,
    photos: [black10, black10_1, black10_2],
    title: 'Calathea Pinstripe',
    stars: 22,
    position: 'New',
    price: 49.0,
    category: 'Indoor',
    color: 'Black',
    potSize: '20-22cm',
    careLevel: 'moderate',
    description:
      'This Calathea Pinstripe is sure to stand out in any collection with its dark green leaves painted with thin pink stripes. As part of the “prayer plant” family, this plant will raise its leaves at night and fan back out during the day in response to lighting. Calatheas need a little bit more attention than hands-off plants, so keep this plant happy in a warm humid spot with the soil kept evenly moist.',
  },
  {
    id: 29,
    img: white11,
    photos: [white11, black4_1, black5],
    title: 'Low Light Bundle',
    stars: 42,
    position: 'bestSellers',
    price: 78.0,
    category: 'Indoor',
    color: 'White',
    potSize: '16cm',
    careLevel: 'hard',
    description:
      'Brighten up any dark space with the vibrant Red Prayer Plant and distinctive Whale Fin Sansevieria. This plant duo is ideal as home office co-workers, mantle show stoppers, or anywhere else there might not be abundant sunshine. These low-light plants are also low-fuss, which makes them perfect for plant parents on the go or thoughtful housewarming gifts.',
  },
  {
    id: 30,
    img: blue6,
    photos: [blue6, gray12_1, gray12_2],
    title: 'Aglaonema Siam',
    stars: 51,
    position: 'New',
    price: 49.0,
    category: 'Indoor',
    color: 'Blue',
    potSize: '12-15cm',
    careLevel: 'hard',
    description:
      'A hardy and gorgeous plant, the Aglaonema Siam features light pink stems and glossy leaves mottled with reds, pinks, and greens. These stunning colors vary depending on the amount of sunlight it gets. Adaptable to a wide range of lighting conditions, it can thrive in nearly any spot within a home.',
  },
  {
    id: 31,
    img: blue7,
    photos: [blue7, black5_2, black5_1],
    title: 'Sympathy Bundle',
    stars: 14,
    position: 'New',
    price: 89.0,
    category: 'Outdoor',
    color: 'Blue',
    potSize: '15-19cm',
    careLevel: 'moderate',
    description:
      'Send a thoughtful, long-lasting message for those experiencing difficult times with the Sympathy Bundle. The Red Prayer Plant and Neon Prayer Plant are a soft reminder that no matter the distance or situation, you’re thinking of them. This pair is easy as far as care goes, so your loved ones can focus their time on self-care.',
  },
  {
    id: 32,
    img: gray8,
    photos: [gray8, black5, black5_1],
    title: 'Red Prayer Plant',
    stars: 67,
    position: 'discounted',
    price: 34.0,
    ExPrice: 49.0,
    category: 'Outdoor',
    color: 'Gray',
    potSize: '20-22cm',
    careLevel: 'easy',
    description: 'Colorful and bold with hints of red on two-toned leaves',
  },
  {
    id: 33,
    img: white12,
    photos: [white12, white12_1, white12_2],
    title: 'Tough Stuff Collection',
    stars: 11,
    position: 'New',
    price: 105.0,
    category: 'Pet Friendly',
    color: 'White',
    potSize: '12.5-15cm',
    careLevel: 'easy',
    description:
      'Three easy and adaptable plants, including a Sansevieria, ZZ Plant, and Hoya variety',
  },
  {
    id: 34,
    img: blue8,
    photos: [blue8, blue8_1, blue8_2],
    title: 'Olive Treen',
    stars: 37,
    position: 'New',
    price: 79.0,
    category: 'Outdoor',
    color: 'Blue',
    potSize: '16cm',
    careLevel: 'moderate',
    description:
      'With shimmering sage-green leaves, the olive tree is ready to add delicate color and texture to your home decor. Hailing from the Mediterranean, this graceful plant will need plenty of bright, direct sunlight to thrive (think sunny, south-facing windows.',
  },
  {
    id: 35,
    img: black11,
    photos: [black11, black11_1, black11_2],
    title: 'Ficus Altissima',
    stars: 35,
    position: 'New',
    price: 145.0,
    category: 'Indoor',
    color: 'Black',
    potSize: '12.5-15cm',
    careLevel: 'moderate',
    description:
      'The detailed leaves of the Ficus Altissima feature variegated tones of green and yellow supported by strong branches. This ficus’ broad look brings an eccentric forest feel to any space. This ficus prefers bright indirect light and to be kept in the same warm spot to grow into its full potential.',
  },
  {
    id: 36,
    img: blue9,
    photos: [blue9, blue9_1, blue9_2],
    title: 'Schefflera Arboricola',
    stars: 46,
    position: 'New',
    price: 169.0,
    category: 'Outdoor',
    color: 'Blue',
    potSize: '12.5-15cm',
    careLevel: 'hard',
    description:
      'With dramatic, umbrella-shaped leaf formations and braided trunk, the Schefflera Arboricola is a no-fuss tree that’s nearly 4 feet tall. Perfect for cozy reading nooks and small spaces where it can receive bright, indirect light. The leaves of the schefflera may vary from fully green to a mix of creamy yellow variegation throughout.',
  },
  {
    id: 37,
    img: gray9,
    photos: [gray9, gray9_1, gray9_2],
    title: 'Lemon Tree',
    stars: 48,
    position: 'bestSellers',
    price: 69.0,
    category: 'Outdoor',
    color: 'Gray',
    potSize: '12.5-15cm',
    careLevel: 'easy',
    description:
      'There’s not much better than pink lemonade on a hot summer day, but we’re fans of enjoying the Pink Variegated Lemon Tree (Citrus limon ‘Eureka Variegated Pink’) every day. With creamy patterned leaves, this petite tree will perk up sunlit windows and your summertime patios.',
  },
  {
    id: 38,
    img: white13,
    photos: [white13, white13_1, white13_2],
    title: 'Silver Bay',
    stars: 81,
    position: 'bestSellers',
    price: 79.0,
    category: 'Pet Friendly',
    color: 'White',
    potSize: '16cm',
    careLevel: 'moderate',
    description:
      'The Aglaonema Silver Bay is one of the most well-known houseplants thanks to its striking green foliage and easy-going nature. Its large leaves are detailed with an icy green center flowing into dark and light green striped edges, retaining their color and pattern in even the lowest lighting conditions.',
  },
  {
    id: 39,
    img: gray10,
    photos: [gray10, gray10_1],
    title: 'Dracaena Warneckii',
    stars: 45,
    position: 'bestSellers',
    price: 112.0,
    category: 'Outdoor',
    color: 'Gray',
    potSize: '12.5-15cm',
    careLevel: 'hard',
    description:
      'The Dracaena Warneckii is a stand-out among Dracaenas with its multi-colored green and creamy white leaves towering above sturdy canes. Known for their carefree care regime, dracaenas are ideal for those who want a lush large plant without all the fuss. The Dracaena Warneckii does well in low to indirect light. Prune off any brown tips on their long leaves as they appear.',
  },
  {
    id: 40,
    img: white5,
    photos: [white5, black4_2, white10_1],
    title: 'Dracaena Duo',
    stars: 28,
    position: 'discounted',
    price: 95.0,
    ExPrice: 110.0,
    category: 'Indoor',
    color: 'White',
    potSize: '15-19cm',
    careLevel: 'moderate',
    description:
      'The Dracaena Warneckii is a stand-out among Dracaenas with its multi-colored green and creamy white leaves towering above sturdy canes. Known for their carefree care regime, dracaenas are ideal for those who want a lush large plant without all the fuss. The Dracaena Warneckii does well in low to indirect light. Prune off any brown tips on their long leaves as they appear.',
  },
  {
    id: 41,
    img: black12,
    photos: [black12, black12_1],
    title: 'Money Tree Forest',
    stars: 51,
    position: 'bestSellers',
    price: 59.0,
    category: 'Indoor',
    color: 'Black',
    potSize: '15-19cm',
    careLevel: 'easy',
    description:
      'The Money Tree Forest is the perfect low-care indoor plant to bring a tropical feel with a touch of good fortune. This grouping of sturdy trunks with their bright green, palm-like leaves offer the look of a lush, mini forest for your home decor. The Money Tree gets its name in part from the natural Feng Shui this plant gives. It’s believed this plant will bring positive energy and good luck to the owner.',
  },
  {
    id: 42,
    img: gray11,
    photos: [gray11, gray11_1, gray11_2],
    title: 'Peace Lily',
    stars: 47,
    position: 'discounted',
    price: 49.0,
    ExPrice: 69.0,
    category: 'Indoor',
    color: 'Gray',
    potSize: '15-19cm',
    careLevel: 'hard',
    description:
      'The Peace Lily has been an iconic houseplant for decades thanks to its forgiving nature, vibrant glossy leaves, and symbolic white blooms. This plant’s large leaves will give any space a lush jungle feeling. The peace lily has come to symbolize prosperity, purity, peace, and sympathy, making it a perfect heartfelt gift.',
  },
  {
    id: 43,
    img: black13,
    photos: [black13, black13_1, black13_2],
    title: 'Baltic Blue Pothos',
    stars: 66,
    position: 'bestSellers',
    price: 69.0,
    category: 'Indoor',
    color: 'Black',
    potSize: '16cm',
    careLevel: 'moderate',
    description:
      'Meet the Baltic Blue Pothos, featuring long, glossy leaves that develop interesting holes, called fenestrations, as it grows. This trailing beauty is the perfect plant for a shelf, windowsill, or as a hanging plant. Its deep green leaves will mature to a blue-green hue. Thriving in bright indirect sunlight, this popular no-fuss plant is a must-have in your collection.',
  },
  {
    id: 44,
    img: blue10,
    photos: [blue10, blue10_1, blue10_2],
    title: 'Bamboo Palm',
    stars: 60,
    position: 'discounted',
    price: 149.0,
    ExPrice: 189.0,
    category: 'Outdoor',
    color: 'Blue',
    potSize: '12.5-15cm',
    careLevel: 'hard',
    description:
      'With dense foliage and lush fronds, the Bamboo Palm makes a statement. An air-purifying plant adaptable to low light, this palm can reach heights of up to 8 feet tall in the right conditions.',
  },
]
export const careToolsData = [
  {
    id: 51,
    img: care1,
    title: 'Watering Can',
    price: 29.0,
    category: 'tool',
    description:
      'This charming Watering Can is a must-have tool in your plant care supplies. Available in a beautiful dark green, each will hold 1.5 liters of water and is made of 100% recyclable plastic. With a removable rainfall head and a traditional design, this classic essential adds both form and function to your gardening arsenal.',
  },
  {
    id: 52,
    img: care2,
    title: 'Plant Care Set',
    price: 55.0,
    category: 'supply',
    description:
      'Everything you need to get into a plant care routine. Includes the Mister to boost humidity, the Microfiber Dusting Gloves to keep your leaves shiny and clean, and Neem Oil to treat your plants for pests or diseases. Our Plant Care Set is sure to encourage more proactive care for your plants.',
  },
  {
    id: 53,
    img: care3,
    title: 'Moss Pole',
    price: 49.0,
    category: 'supply',
    description:
      'Celebrate the natural forms of nature with this unique 30” bendable Moss Pole. Its adjustable design allows you to train your climbing plants in any direction you wish while providing control and stabilization. This bendable moss pole allows the freedom for your plant to grow in many different directions. It’s great for monsteras, philodendrons, pothos, and other climbing plants. Pins are included.',
  },
  {
    id: 65,
    img: potcare3,
    title: 'White',
    price: 17.0,
    category: 'pot',
    description:
      'Is your plant ready for more space? Encourage growth and healthy root development by repotting your root-bound plant with our Repotting Kit. This kit includes one 10” round Ecopot and one 8-quart bag of our premium potting soil. Your plant will flourish with the additional space.',
  },
  {
    id: 55,
    img: care5,
    title: 'Gloves',
    price: 12.0,
    category: 'tool',
    description:
      'An easy, efficient way to keep dust and other debris off of your plants’ leaves, allowing for sunlight to be absorbed more easily for better plant health.',
  },
  {
    id: 56,
    img: care6,
    title: 'Dusting Gloves',
    price: 15.0,
    category: 'tool',
    description:
      'Microfiber gloves are an easy, efficient way to keep dust and other debris off of your plants’ leaves, allowing for sunlight to be absorbed more easily for better plant health.',
  },
  {
    id: 73,
    img: care19,
    title: 'Time Release ClassiCote',
    price: 35.0,
    category: 'supply',
    description:
      'This nutrient-rich fertilizer works wonders on both indoor and outdoor plants. Releasing nutrients slowly over 4 months, Jack’s ClassiCote Fertilizer is the ideal selection for forgetful plant parents and plants that resent being over-fertilized.',
  },
  {
    id: 57,
    img: care7,
    title: 'Mister',
    price: 40.0,
    category: 'tool',
    description:
      'Increase humidity for your plants using the fully rechargeable Mossify Mistr. With one click, you will have a continuous fine mist to provide extra humidity to all of your tropical foliage. With a capacity of 750ml, this sleek and stylish mister will have your plants thanking you for the additional moisture in the air.',
  },
  {
    id: 58,
    img: care8,
    title: 'Snips',
    price: 15.0,
    category: 'tool',
    description:
      'These snips work well for plants with medium-sized stems, such as philodendrons, pothos, tradescantias, and sansevierias. Wipe the blades with rubbing alcohol between each snip to avoid spreading any bacteria between plants.',
  },
  {
    id: 72,
    img: care18,
    title: ' Rooting Hormone',
    price: 10.0,
    category: 'supply',
    description:
      'Expand your plant family with the help of this TakeRoot® Rooting Hormone to promote healthy root development. Propagate your favorite indoor plants by taking a cutting of your plant, dipping the end in the powder, then putting the cutting in a glass of water. Watch your roots start to grow within a few weeks! Gift your new plant or keep it for yourself to grow your collection.',
  },
  {
    id: 64,
    img: potcare2,
    title: 'Black',
    price: 19.0,
    category: 'pot',
    description:
      'Is your plant ready for more space? Encourage growth and healthy root development by repotting your root-bound plant with our Repotting Kit. This kit includes one 10” round Ecopot and one 8-quart bag of our premium potting soil. Your plant will flourish with the additional space.',
  },
  {
    id: 59,
    img: care9,
    title: 'Cutting Tool',
    price: 22.0,
    category: 'tool',
    description:
      'This double-edged Cutting Tool is useful for repotting, transplanting, weeding, and maintaining your garden. Dig precise holes or easily uproot weeds with its sharp edges. Use the serrated side to slice through unruly roots or tangled stems. Featuring depth markings on the blade, it allows for accurate planting. This versatile cutting tool is highly recommended for any gardener.',
  },
  {
    id: 60,
    img: care10,
    title: 'Pruning Scissors',
    price: 25.0,
    category: 'tool',
    description:
      'These high-quality stainless steel Pruning Scissors are excellent for trimming those hard-to-reach places. Use these scissors to prune your small plants with thinner stems such as ferns, hoyas, and herbs. These are also useful for trimming leaves on calatheas, prayer plants, palms, dracaenas, and more. Wipe the blades with rubbing alcohol between each snip to avoid spreading any bacteria between plants. Useful for outdoor gardening as well.',
  },
  {
    id: 61,
    img: care11,
    title: 'Hand Trowel',
    price: 19.0,
    category: 'tool',
    description:
      'This versatile Hand Trowel is useful for repotting and planting both indoors and out. With a wide, deep dish and narrow tip, this tool will dig, transplant, and scoop soil with ease. Excellent for smaller plants and pots, as well as outdoor gardening, this high-quality, stainless steel tool is great to have on-hand for all your gardening needs.',
  },
  {
    id: 62,
    img: care12,
    title: 'Potting Soil',
    price: 20.0,
    category: 'supply',
    description:
      'Repot your plants with Bloomscape’s signature potting soil. Our mix will help your plants retain water moisture and provide proper drainage for happier, healthier roots.',
  },
  {
    id: 63,
    img: potcare1,
    title: 'Blue',
    price: 17.0,
    category: 'pot',
    description:
      'Is your plant ready for more space? Encourage growth and healthy root development by repotting your root-bound plant with our Repotting Kit. This kit includes one 10” round Ecopot and one 8-quart bag of our premium potting soil. Your plant will flourish with the additional space.',
  },
  {
    id: 74,
    img: care20,
    title: 'Superthrive',
    price: 18.0,
    category: 'supply',
    description:
      'Superthrive is a must-have product for any plant parent. This product is small but mighty since a little amount goes a long way. It is specially formulated to nourish and strengthen newly transplanted or repotted plants, revive stressed plants, and help with general plant maintenance. This non-toxic, natural vitamin solution can simply be added to the water you are using to water your plants, acting quickly to make your foliage friends happy.',
  },

  {
    id: 67,
    img: care13,
    title: 'Beginner Gardening Tool Set',
    price: 89.0,
    category: 'tool',
    description:
      'The ideal gift for the new plant collector in your life, the Beginner Gardening Tool Set set has a hand trowel, plant pruners, and plant snips that neatly roll up in the included tool roll. This set is great for beginner plant parents who need a few essential tools and want to keep them organized and tidy.',
  },
  {
    id: 68,
    img: care14,
    title: 'Complete Gardening Tool Set',
    price: 119.0,
    category: 'tool',
    description:
      'Our Complete Gardening Tool Set includes everything you need for pruning, harvesting, trimming, repotting, and planting. An ideal gift for the budding avid gardener to set them up for a successful long-term relationship caring for their plants.',
  },
  {
    id: 75,
    img: potcare5,
    title: 'All Pots',
    price: 59.0,
    category: 'pot',
    description:
      'Is your plant ready for more space? Encourage growth and healthy root development by repotting your root-bound plant with our Repotting Kit. This kit includes one 10” round Ecopot and one 8-quart bag of our premium potting soil. Your plant will flourish with the additional space.',
  },

  {
    id: 69,
    img: care15,
    title: 'Soil Scoop',
    price: 30.0,
    category: 'tool',
    description:
      'This stainless steel Soil Scoop is an essential tool for repotting and planting both indoor and outdoor plants. This tool allows you to move generous amounts of soil at once and is helpful for mixing in slow-release fertilizer as you repot. Add this useful tool to your collection and repot your plants with ease.',
  },
  {
    id: 66,
    img: potcare4,
    title: 'Gray',
    price: 18.0,
    category: 'pot',
    description:
      'Is your plant ready for more space? Encourage growth and healthy root development by repotting your root-bound plant with our Repotting Kit. This kit includes one 10” round Ecopot and one 8-quart bag of our premium potting soil. Your plant will flourish with the additional space.',
  },
  {
    id: 70,
    img: care16,
    title: 'Plant Pruner',
    price: 19.0,
    category: 'tool',
    description:
      'This high-quality stainless steel Plant Pruner easily cuts large stems and tough branches. From woody houseplants to outdoor shrubs and trees, this tool is useful for any gardener. Great for pruning your ficus, norfolk pine, schefflera, ZZ plant, and other larger plants. Wipe the blades with rubbing alcohol between each snip to avoid spreading any bacteria between plants.',
  },
  {
    id: 71,
    img: care17,
    title: 'Neem Oil',
    price: 15.0,
    category: 'supply',
    description:
      'Bonide Neem Oil is an all-purpose insecticide, miticide, and fungicide for organic gardening. Neem oil is great for plant owners to have on hand to treat active pests and diseases and prevent future outbreaks.',
  },
]
export const illustrationData = [
  {
    id: uuidv4(),
    img: illustration1,
    title: 'course',
    textBold: 'All the help you need',
    description:
      ' We’ll send you a free plant-parenting course and our plant doctors are always on call.',
  },
  {
    id: uuidv4(),
    img: illustration2,
    title: 'delivery',
    textBold: 'Delivery to your door',
    description:
      " We'll bring your plants to your door, anywhere in GB. If you’re not 100% happy, tell us in 30 days and we’ll sort it..",
  },
  {
    id: uuidv4(),
    img: illustration3,
    title: 'quality',
    textBold: 'Unbeatable quality',
    description:
      'We source directly from top-rated growers, so we can sell the finest quality plants at the very best prices.',
  },
]
export const potsData=[
  {
    img: pot1,
    name: 'Colorful',
  },
    {
    img: pot2,
    name: 'Jungle',
  },
    {
    img: pot3,
    name: 'Cottage',
  },
    {
    img: pot4,
    name: 'Edible',
  },
    {
    img: pot5,
    name: 'Mediterranean',
  },
    {
    img: pot6,
    name: 'Renter friendly',
  },
    {
    img: pot7,
    name: 'Autumn Interest',
  },
    {
    img: pot8,
    name: 'Winter Interest',
  }
]
export const ReviewsData = [
  {
    id: uuidv4(),
    date: '06/09/23',
    title: 'Fast and quality shipping; well',
    content:
      'I would highly recommend. Their attention to detail, excellent packaging, and healthy plants make them stand out among other online plant retailers',
    author: 'Barbara W.',
  },
  {
    id: uuidv4(),
    date: '01/09/23',
    title: 'Fast and quality shipping; well',
    content:
      'The website is clear and full of information. Plants are carefully packaged and are healthy with lots of advice about plant care.',
    author: 'Clare Swanepoel',
  },
  {
    id: uuidv4(),
    date: '24/08/23',
    title: 'Fast and quality shipping; well',
    content:
      'Fantastic choice of plants on the website each with a very good amount of information on things such as where the plant is best situated.',
    author: 'MR HARRY CLEMENTSON',
  },
  {
    id: uuidv4(),
    date: '15/08/23',
    title: 'Fast and quality shipping; well',
    content:
      ' A customer service was excellent in sorting this out and couldn’t do anymore. They were genuinely interested in helping me.',
    author: 'Kathleen Brennan',
  },
  {
    id: uuidv4(),
    date: '04/08/23',
    title: 'Fast and quality shipping; well',
    content:
      'The plants arrive very well packed and in excellent condition. Website gives great information for each plant. ',
    author: 'Nicola Horner',
  },
  {
    id: uuidv4(),
    date: '30/07/23',
    title: 'Fast and quality shipping; well',
    content:
      'Excellent customer service. Plants arrive very well packed and in excellent condition. Website gives great information for each plant.',
    author: 'Cameron Wilson',
  },
  {
    id: uuidv4(),
    date: '19/07/23',
    title: 'Fast and quality shipping; well',
    content:
      'The packaging was great, so even when the delivery people decided to keep it upside down, the plant was still in great shape.',
    author: 'happy gardener Sue',
  },
  {
    id: uuidv4(),
    date: '05/07/23',
    title: 'Fast and quality shipping; well',
    content:
      'The plants arrived looking very healthy and were delivered exactly when I was told they would. They have settled in well.',
    author: 'Barbara W.',
  },
  {
    id: uuidv4(),
    date: '02/07/23',
    title: 'Fast and quality shipping; well',
    content:
      'The website is clear and full of information. Plants are carefully packaged and are healthy with lots of advice about plant care.',
    author: 'Sarah Stitson',
  },
  {
    id: uuidv4(),
    date: '22/06/23',
    title: 'Fast and quality shipping; well',
    content:
      'Great looking plants, one pot broken on arrival, but replacement sent with no quibble',
    author: 'Leigh Law,',
  },
  {
    id: uuidv4(),
    date: '16/06/23',
    title: 'Fast and quality shipping; well',
    content:
      'What impressed me the most was the attention to detail that Patch demonstrated in their packaging and shipping process.',
    author: 'Snow Wight',
  },
  {
    id: uuidv4(),
    date: '03/06/23',
    title: 'Fast and quality shipping; well',
    content:
      'The information on the website is excellent - both the care and the history of the plant. Recipients have been very happy too. Thoroughly recommend.',
    author: 'susan Black',
  },
]
export const giftsProductsData = [
  {
    id: 31,
    img: gift1,
    title: 'Sympathy Bundle',
    price: 89.0,
    stars: 14,
    description:
      'Send a thoughtful, long-lasting message for those experiencing difficult times with the Sympathy Bundle. The Red Prayer Plant and Neon Prayer Plant are a soft reminder that no matter the distance or situation, you’re thinking of them. This pair is easy as far as care goes, so your loved ones can focus their time on self-care. Prayer Plants can be placed in low to indirect light making them ideal for almost any space.',
  },
  {
    id: 27,
    img: gift2,
    title: 'Kitchen Bundle',
    price: 82.0,
    stars: 12,
    description:
      'Turn some heads and brighten up your home with the Statement Bundle featuring the Bromeliad Aechmea Pink and Bromeliad Pineapple. This eccentric duo brings a warm vibe that makes you feel like you’ve been whisked off to a tropical destination. The fun Bromeliad Aechmea Pink and Bromeliad Pineapple are hands-off, letting you enjoy your indoor jungle without frequent maintenance. These two are sure to be the talk of the town or maybe just your next dinner party.',
  },
  {
    id: 21,
    img: white9,
    title: 'Felicity',
    stars: 23,
    price: 68.0,
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Est et minus, maxime, dicta adipisci suscipit quis explicabo facilis veritatis quisquam iure omnis maiores sed temporibus error nesciunt autem asperiores aspernatur.',
  },
  {
    id: 25,
    img: black9,
    title: 'Mini Beginner Set',
    stars: 41,
    price: '116.00',
    description:
      'Whether you’re just starting your plant parent journey or you want to help a loved one get started on theirs, the Mini Beginner set has you covered. Meet the easy-going Hedgehog Aloe, delightful Money Tree, and classic Philodendron Heartleaf.',
  },
  {
    id: 40,
    img: white5,
    title: 'Dracaena Duo',
    stars: 28,
    price: 95.0,
    description:
      'The Dracaena Warneckii is a stand-out among Dracaenas with its multi-colored green and creamy white leaves towering above sturdy canes. Known for their carefree care regime, dracaenas are ideal for those who want a lush large plant without all the fuss. The Dracaena Warneckii does well in low to indirect light. Prune off any brown tips on their long leaves as they appear.',
  },
  {
    id: 14,
    img: blue3,
    title: 'Money Tree',
    stars: 36,
    price: 69.0,
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Est et minus, maxime, dicta adipisci suscipit quis explicabo facilis veritatis quisquam iure omnis maiores sed temporibus error nesciunt autem asperiores aspernatur.',
  },
  {
    id: 37,
    img: gray9,
    title: 'Lemon Tree',
    stars: 48,
    price: 69.0,
    description:
      'There’s not much better than pink lemonade on a hot summer day, but we’re fans of enjoying the Pink Variegated Lemon Tree (Citrus limon ‘Eureka Variegated Pink’) every day. With creamy patterned leaves, this petite tree will perk up sunlit windows and your summertime patios.',
  },
  {
    id: 5,
    img: blue1,
    title: 'Guzmania',
    price: '75.00',
    stars: 21,
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Est et minus, maxime, dicta adipisci suscipit quis explicabo facilis veritatis quisquam iure omnis maiores sed temporibus error nesciunt autem asperiores aspernatur.',
  },
  {
    id: 6,
    img: white2,
    title: 'Peace Lily',
    price: 75.0,
    stars: 14,
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Est et minus, maxime, dicta adipisci suscipit quis explicabo facilis veritatis quisquam iure omnis maiores sed temporibus error nesciunt autem asperiores aspernatur.',
  },
]
export const giftArticlesData = [
  {
    id: uuidv4(),
    img: giftCover2,
    title: 'There’s a plant for every person',
    article:
      'They could be a home bird or always on the go. They might be pattern-crazy or a little more minimalist. Perhaps they live in a big house in the country, or have a small space in the city. Whoever you want to send a present to, you can guarantee there’s a plant that’s exactly right for them. ',
    articleBr:
      'For small homes, choose a hanging plant, like Rapunzel the golden pothos or Emma the tradescantia nanouk, to optimise space. And for people with busy schedules, go for easy care or (almost) unkillable plants like Apollo the snake plant, or Sharon the parlour palm.',
  },
  {
    id: uuidv4(),
    img: giftCover3,
    title: 'And for every occasion',
    article:
      'If you’re welcoming a newborn or a new pet, there are lots of pet-and-baby-friendly plants that can grow up alongside them – like Howard the cast iron plant or Bertie the Boston fern. For birthdays, go for something bold to celebrate another year of life in style – like Zabrina the elephant ear, or Rob the rubber plant. To add a bit of zest to a new home, Vivi the lemon tree makes for a memorable (and delicious) gift.  ',
    articleBr:
      'Whatever you’re celebrating, plants make a great present because there’s such a wide variety to choose from. Bonus? You never have to worry about gifting the same thing as someone else.',
  },
  {
    id: uuidv4(),
    img: giftCover4,
    title: 'Plants can send the right message',
    article:
      'If you want to wish someone some good fortune, you could give them a money plant like Penny the pilea. Peace lilies like Pippa, unsurprisingly, signify peace and sympathy, and calatheas like Julia can symbolise gratitude and new beginnings. Plants have become loaded with meaning over time, so if you can’t put something into words, gifting a plant can do it for you. ',
  },
  {
    id: uuidv4(),
    img: giftCover5,
    title: '‘Wrap’ it in something beautiful',
    article:
      'An extra way to elevate your present is by sending it off ‘wrapped’ in its own pot. Create a refined look with minimalist concrete pots. For something more textural, opt for a fractured pot. Or play with colour – with two-toned dipped pots or ceramic glazed pots that come in stone, blue and mint. Plant pots are a great way to round off an already amazing present and they’re far more practical (and sustainable) than wrapping paper.  ',
    articleBr:
      'We’ve put together some stylish gift sets to help you decide on the right plant-and-pot pairings for the person you have in mind. ',
  },
  {
    id: uuidv4(),
    img: giftCover6,
    title: 'Plants brighten rooms – and moods',
    article:
      'Giving someone a living thing that they can nurture and look after encourages mindfulness, eases anxiety and helps focus. Many scientific studies support the idea that plants can improve our mental health and help to lift us up. This makes your present not just something nice to look at – it actually has fantastic therapeutic benefits too. ',
    articleBr:
      'To make plant care even easier, many of our gift sets include accessories for misting, watering, and pruning plants.  ',
  },
]
export const workshopsData = [
  {
    id: uuidv4(),
    img: workshopImg1,
    title: 'Happy Hour Sip n Shop: Cobble Hill',
    date: 'July 28th, 2023',
    content:
      'Join us at our Cobble Hill, BK location for a Happy Hour Sip & Shop! Enjoy complimentary drinks and 10% off The Sill plants and products.',
  },
  {
    id: uuidv4(),
    img: workshopImg2,
    title: 'Happy Hour Sip n Shop: Park Slope',
    date: 'July 28th, 2023',
    content:
      'Join us at our Park Slope, BK location for a Happy Hour Sip & Shop! Enjoy complimentary drinks and 10% off The Sill plants and products.',
  },
  {
    id: uuidv4(),
    img: workshopImg3,
    title: 'Happy Hour Sip n Shop: UWS',
    date: 'July 28th, 2023',
    content:
      'Join us at our UWS, NYC location for a Happy Hour Sip & Shop! Enjoy complimentary drinks and 10% off The Sill plants and products.',
  },
  {
    id: uuidv4(),
    img: workshopImg4,
    title: 'Happy Hour Sip n Shop: Williamsburg',
    date: 'July 28th, 2023',
    content:
      'Join us at our Williamsburg, BK location for a Happy Hour Sip & Shop! Enjoy complimentary drinks and 10% off The Sill plants and products.',
  },
  {
    id: uuidv4(),
    img: workshopImg5,
    title: 'Happy Hour Sip n Shop: Chicago',
    date: 'July 28th, 2023',
    content:
      'Join us at our Chicago, IL location for a Happy Hour Sip & Shop! Enjoy complimentary drinks and 10% off The Sill plants and products.',
  },
  {
    id: uuidv4(),
    img: workshopImg6,
    title: 'Happy Hour Sip n Shop: San Francisco',
    date: 'July 29th, 2023',
    content:
      'Join us at our San Francisco, CA location for a Happy Hour Sip & Shop! Enjoy complimentary drinks and 10% off The Sill plants and products.',
  },
  {
    id: uuidv4(),
    img: workshopImg7,
    title: 'Happy Hour Sip n Shop: In Person Workshop in Bethesda ',
    date: 'July 29th, 2023',
    content:
      'Join us at our Bethesda, MD location for a Happy Hour Sip & Shop! Enjoy complimentary drinks and 10% off The Sill plants and products. ',
  },
  {
    id: uuidv4(),
    img: workshopImg8,
    title: 'Christmas in July: White Elephant Plant Swap in Williamsburg',
    date: 'July 29th, 2023',
    content:
      'Join The Sill for a Christmas in July: White Elephant Plant Swap in Williamsburg! Enjoy participating in a plant gift exchange.',
  },
  {
    id: uuidv4(),
    img: workshopImg9,
    title: 'Propagation 101: In Person Workshop in Bethesda',
    date: 'July 31st, 2023',
    content:
      'Join The Sill for a free Propagation 101 Workshop in Bethesda ! Learn how to successfully propagate your plants using different methods.',
  },
]
export const workshopsAdvertData = [
  {
    id: uuidv4(),
    img: takeCare1,
    title: 'course',
    textBold: 'All the help you need',
    description:
      ' We’ll send you a free plant-parenting course and our plant doctors are always on call.',
  },
  {
    id: uuidv4(),
    img: takeCare2,
    title: 'course',
    textBold: 'All the help you need',
    description:
      ' We’ll send you a free plant-parenting course and our plant doctors are always on call.',
  },
  {
    id: uuidv4(), 
    img: takeCare3,
    title: 'course',
    textBold: 'All the help you need',
    description:
      ' We’ll send you a free plant-parenting course and our plant doctors are always on call.',
  },
]
export const eventsData = [
  {
    id: uuidv4(),
    img: workshopImg1,
    title: 'Happy Hour Sip n Shop: Cobble Hill',
    date: 'July 28th, 2023',
    content:
      'Join us at our Cobble Hill, BK location for a Happy Hour Sip & Shop! Enjoy complimentary drinks and 10% off The Sill plants and products.',
  },
  {
    id: uuidv4(),
    img: workshopImg2,
    title: 'Happy Hour Sip n Shop: Park Slope',
    date: 'July 28th, 2023',
    content:
      'Join us at our Park Slope, BK location for a Happy Hour Sip & Shop! Enjoy complimentary drinks and 10% off The Sill plants and products.',
  },
  {
    id: uuidv4(),
    img: workshopImg3,
    title: 'Happy Hour Sip n Shop: UWS',
    date: 'July 28th, 2023',
    content:
      'Join us at our UWS, NYC location for a Happy Hour Sip & Shop! Enjoy complimentary drinks and 10% off The Sill plants and products.',
  },

  {
    id: uuidv4(),
    img: workshopImg7,
    title: 'Happy Hour Sip n Shop: In Person Workshop in Bethesda ',
    date: 'July 29th, 2023',
    content:
      'Join us at our Bethesda, MD location for a Happy Hour Sip & Shop! Enjoy complimentary drinks and 10% off The Sill plants and products. ',
  },
  {
    id: uuidv4(),
    img: workshopImg8,
    title: 'Christmas in July: White Elephant Plant Swap in Williamsburg',
    date: 'July 29th, 2023',
    content:
      'Join The Sill for a Christmas in July: White Elephant Plant Swap in Williamsburg! Enjoy participating in a plant gift exchange.',
  },
  {
    id: uuidv4(),
    img: workshopImg9,
    title: 'Propagation 101: In Person Workshop in Bethesda',
    date: 'July 31st, 2023',
    content:
      'Join The Sill for a free Propagation 101 Workshop  in Bethesda ! Learn how to successfully propagate your plants using different methods.',
  },
]

